import { randomUUID } from "node:crypto";
import type { IncomingMessage, ServerResponse } from "node:http";

import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import type { AuthInfo } from "@modelcontextprotocol/sdk/server/auth/types.js";

import { AGENT_HIERARCHY_RESOURCE_URI, type McpApplication } from "./app.js";

/** The exact public surface exposed by Agent Farm's MCP application. */
export const AGENT_FARM_MCP_TOOL_NAMES = [
  "create_agent_session",
  "get_agent_hierarchy",
  "get_agent_details",
  "render_agent_hierarchy",
] as const;

export type AgentFarmMcpToolName = (typeof AGENT_FARM_MCP_TOOL_NAMES)[number];

/** Re-export the SDK type without requiring HTTP consumers to depend on it directly. */
export type McpAuthInfo = AuthInfo;

export type McpNodeRequest = IncomingMessage & { auth?: AuthInfo };

/**
 * Verified, refresh-stable OAuth grant identity. `jti` is intentionally absent:
 * it rotates on refresh and is never part of the durable session key.
 */
export interface McpGrantSessionBindingKey {
  readonly ownerId: string;
  readonly tenantId: string;
  readonly subject: string;
  readonly resource: string;
  readonly grantId: string;
}

export interface McpGrantSessionBindingRequest extends McpGrantSessionBindingKey {
  /** Candidate generated by the MCP manager; the durable winner is authoritative. */
  readonly proposedAgentSessionId: string;
  /** Verified token expiration in milliseconds, when available. */
  readonly expiresAt?: number;
}

export interface McpGrantSessionBindingRecord {
  readonly agentSessionId: string;
  readonly status: "active" | "revoked" | "expired";
  readonly expiresAt: number;
}

/**
 * Async boundary for durable grant continuity. Implementations must atomically
 * get-or-create by the grant tuple and must never persist bearer/jti/token
 * material. `get` is optional for adapters that do not expose live revocation;
 * production composition supplies it so revocation fails closed on every
 * remount/request.
 */
export interface McpGrantSessionBindingStore {
  getOrCreate(
    input: McpGrantSessionBindingRequest,
  ): McpGrantSessionBindingRecord | null | Promise<McpGrantSessionBindingRecord | null>;
  get?(
    input: McpGrantSessionBindingKey,
  ): McpGrantSessionBindingRecord | null | Promise<McpGrantSessionBindingRecord | null>;
}

export interface McpHttpApplicationFactory {
  /** Return a fresh McpApplication for one MCP protocol session. */
  (): McpApplication;
}

/**
 * Bounds and clocks for the in-memory MCP session registry.
 *
 * Session entries retain only the verified identity tuple and the SDK
 * application/transport.  They never retain the bearer token or an AuthInfo
 * object, since AuthInfo contains the raw access token.
 */
export interface McpHttpSessionManagerOptions {
  readonly applicationFactory: McpHttpApplicationFactory;
  /** Idle lifetime in milliseconds. Defaults to 15 minutes. */
  readonly sessionTtlMs?: number;
  /** Alias accepted by small integrations/tests. */
  readonly ttlMs?: number;
  /** Maximum live protocol sessions. Defaults to 128. */
  readonly maxSessions?: number;
  /** Injectable clock for deterministic expiry tests. */
  readonly now?: () => number;
  /** Injectable opaque MCP-session ID source. */
  readonly sessionIdGenerator?: () => string;
  /** Injectable server-selected Agent Farm session ID source. */
  readonly agentSessionIdGenerator?: () => string;
  /** Durable identity mapping for the verified OAuth grant, when available. */
  readonly grantSessionBindingStore?: McpGrantSessionBindingStore;
}

export interface McpHttpHandlerOptions {
  /** A manager should be created once for the owning Fastify/application instance. */
  readonly sessionManager?: McpHttpSessionManager;
  /**
   * Compatibility path for direct Node adapters. When no explicit manager is
   * supplied, a manager is cached by factory identity rather than recreated
   * per request. Production composition passes `sessionManager` explicitly.
   */
  readonly applicationFactory?: McpHttpApplicationFactory;
  readonly enableJsonResponse?: boolean;
  readonly allowedHosts?: readonly string[];
  readonly allowedOrigins?: readonly string[];
  readonly keepAliveMs?: number;
}

interface SessionBinding {
  readonly ownerId: string;
  readonly tenantId: string;
  readonly subject: string;
  /** Refresh-stable OAuth grant/session identifier (for example `sid`). */
  readonly grantId: string;
  readonly jti: string;
  readonly resource: string;
}

interface SessionEntry {
  readonly mcpSessionId: string;
  readonly agentSessionId: string;
  readonly binding: SessionBinding;
  readonly application: McpApplication;
  readonly transport: StreamableHTTPServerTransport;
  lastActivityAt: number;
  closed: boolean;
}

interface TransportOptions {
  readonly enableJsonResponse: boolean;
  readonly allowedHosts?: readonly string[];
  readonly allowedOrigins?: readonly string[];
  readonly keepAliveMs?: number;
}

const DEFAULT_SESSION_TTL_MS = 15 * 60 * 1_000;
const DEFAULT_MAX_SESSIONS = 128;
const MAX_SESSION_ID_LENGTH = 256;
const MAX_CLAIM_LENGTH = 256;

/**
 * Bounded, owner-bound registry for official stateful SDK transports.
 *
 * One registry belongs to one HTTP composition root. Each initialize request
 * creates one fresh McpApplication + StreamableHTTPServerTransport pair. All
 * later requests must present the SDK-issued MCP-Session-Id and the same
 * verified identity tuple before the request reaches the transport.
 */
export class McpHttpSessionManager {
  private readonly applicationFactory: McpHttpApplicationFactory;
  private readonly sessionTtlMs: number;
  private readonly maxSessions: number;
  private readonly now: () => number;
  private readonly sessionIdGenerator: () => string;
  private readonly agentSessionIdGenerator: () => string;
  private readonly grantSessionBindingStore: McpGrantSessionBindingStore | undefined;
  private readonly entries = new Map<string, SessionEntry>();
  private closed = false;

  constructor(options: McpHttpSessionManagerOptions) {
    this.applicationFactory = options.applicationFactory;
    this.sessionTtlMs = boundedPositive(options.sessionTtlMs ?? options.ttlMs ?? DEFAULT_SESSION_TTL_MS, "sessionTtlMs");
    this.maxSessions = boundedPositiveInteger(options.maxSessions ?? DEFAULT_MAX_SESSIONS, "maxSessions");
    this.now = options.now ?? Date.now;
    this.sessionIdGenerator = options.sessionIdGenerator ?? randomUUID;
    this.agentSessionIdGenerator = options.agentSessionIdGenerator ?? randomUUID;
    this.grantSessionBindingStore = options.grantSessionBindingStore;
  }

  /** Number of live sessions after a best-effort expiry sweep. */
  get size(): number {
    this.evictExpiredSync();
    return this.entries.size;
  }

  /** Deterministic inspection hook that exposes no identity/token material. */
  has(mcpSessionId: string): boolean {
    this.evictExpiredSync();
    return this.entries.has(mcpSessionId);
  }

  /**
   * Close every transport/application and release all registry state. Safe to
   * call repeatedly and intended for Fastify's `onClose` hook.
   */
  async cleanup(): Promise<void> {
    this.closed = true;
    const entries = [...this.entries.values()];
    this.entries.clear();
    await Promise.all(entries.map((entry) => this.closeEntry(entry, true)));
  }

  /** Alias used by generic server shutdown adapters. */
  async close(): Promise<void> {
    await this.cleanup();
  }

  /**
   * Dispatch one request. The manager owns transport lifetime; callers must
   * not close a transport after this method returns.
   */
  async handleRequest(
    request: McpNodeRequest,
    response: ServerResponse,
    parsedBody: unknown,
    options: Omit<McpHttpHandlerOptions, "sessionManager" | "applicationFactory">,
  ): Promise<void> {
    await this.evictExpired();

    const sessionHeader = readMcpSessionId(request);
    if (sessionHeader.present) {
      if (sessionHeader.value === undefined) {
        writeMcpError(response, 404, -32001, "Session not found");
        return;
      }
      await this.handleExistingSession(request, response, parsedBody, sessionHeader.value);
      return;
    }

    // A stateful SDK transport itself rejects non-initialize POSTs without a
    // session ID. Reject GET/DELETE here so they cannot create an application.
    if (request.method !== "POST") {
      writeMcpError(response, 400, -32000, "Mcp-Session-Id header is required");
      return;
    }

    // Fastify normally supplies a parsed body. Avoid constructing an SDK
    // application for a known non-initialize request that omitted its
    // required protocol-session header. When no body was pre-parsed, the SDK
    // remains the source of truth and rejects it after the candidate closes.
    if (parsedBody !== undefined && !containsInitializeRequest(parsedBody)) {
      writeMcpError(response, 400, -32000, "Mcp-Session-Id header is required");
      return;
    }

    const binding = bindingFromAuthInfo(request.auth);
    if (binding === undefined) {
      writeMcpError(response, 401, -32001, "Authorization is required");
      return;
    }

    await this.handleInitialization(request, response, parsedBody, binding, options);
  }

  private async handleInitialization(
    request: McpNodeRequest,
    response: ServerResponse,
    parsedBody: unknown,
    binding: SessionBinding,
    options: Omit<McpHttpHandlerOptions, "sessionManager" | "applicationFactory">,
  ): Promise<void> {
    if (this.closed) {
      writeMcpError(response, 503, -32001, "MCP session manager is closed");
      return;
    }

    const proposedAgentSessionId = boundedOpaqueId(this.agentSessionIdGenerator(), "agentSessionId");
    const durableBinding = await this.resolveGrantSessionBinding(binding, proposedAgentSessionId, request.auth);
    if (this.grantSessionBindingStore !== undefined && (durableBinding === undefined || durableBinding === null || durableBinding.status !== "active")) {
      // A revoked/expired binding is deliberately indistinguishable from an
      // unknown grant. Do not disclose whether a durable mapping existed.
      writeMcpError(response, 404, -32001, "Session not found");
      return;
    }
    const agentSessionId = boundedOpaqueId(
      durableBinding?.agentSessionId ?? proposedAgentSessionId,
      "agentSessionId",
    );

    const application = this.applicationFactory();
    assertPublicApplication(application);
    const transportOptions = toTransportOptions(options);
    let entry: SessionEntry | undefined;
    let initializedSessionId: string | undefined;

    const transport = new StreamableHTTPServerTransport({
      sessionIdGenerator: () => {
        const generated = boundedOpaqueId(this.sessionIdGenerator(), "MCP session ID");
        if (generated === agentSessionId) {
          throw new Error("MCP and Agent Farm session IDs must be distinct");
        }
        return generated;
      },
      onsessioninitialized: async (mcpSessionId) => {
        initializedSessionId = boundedOpaqueId(mcpSessionId, "MCP session ID");
        const next: SessionEntry = {
          mcpSessionId: initializedSessionId,
          agentSessionId,
          binding,
          application,
          transport,
          lastActivityAt: this.now(),
          closed: false,
        };
        await this.register(next);
        entry = next;
      },
      onsessionclosed: async (mcpSessionId) => {
        const current = this.entries.get(mcpSessionId);
        if (current !== undefined && current.transport === transport) {
          this.entries.delete(mcpSessionId);
          current.closed = true;
          // The SDK closes the transport immediately after this callback. Do
          // not close it recursively; close the application connection only.
          await closeApplication(current.application);
        }
      },
      enableJsonResponse: transportOptions.enableJsonResponse,
      ...(transportOptions.allowedHosts === undefined ? {} : { allowedHosts: [...transportOptions.allowedHosts] }),
      ...(transportOptions.allowedOrigins === undefined ? {} : { allowedOrigins: [...transportOptions.allowedOrigins] }),
      ...(transportOptions.allowedHosts !== undefined || transportOptions.allowedOrigins !== undefined
        ? { enableDnsRebindingProtection: true }
        : {}),
      ...(transportOptions.keepAliveMs === undefined ? {} : { keepAliveMs: transportOptions.keepAliveMs }),
    });

    try {
      await connectApplication(application, transport);
      await transport.handleRequest(request, response, parsedBody);
      // A malformed/non-initialize POST is rejected by the SDK before a
      // session callback fires. Release the candidate app/transport in that
      // case instead of retaining an unbounded orphan.
      if (entry === undefined) {
        await closeApplication(application);
        await closeTransport(transport);
      } else {
        entry.lastActivityAt = this.now();
      }
    } catch (error) {
      if (entry !== undefined) {
        this.entries.delete(entry.mcpSessionId);
        entry.closed = true;
      }
      await closeApplication(application);
      await closeTransport(transport);
      throw error;
    }

    // Keep this local read to make it explicit that registration is callback
    // driven; no request or conversation value selects the session ID.
    void initializedSessionId;
  }

  private async handleExistingSession(
    request: McpNodeRequest,
    response: ServerResponse,
    parsedBody: unknown,
    mcpSessionId: string,
  ): Promise<void> {
    const entry = this.entries.get(mcpSessionId);
    if (entry === undefined || entry.closed) {
      writeMcpError(response, 404, -32001, "Session not found");
      return;
    }
    if (this.isExpired(entry)) {
      await this.removeEntry(entry);
      writeMcpError(response, 404, -32001, "Session not found");
      return;
    }

    const binding = bindingFromAuthInfo(request.auth);
    if (binding === undefined) {
      // Do not disclose whether this opaque ID exists to unauthenticated
      // callers. Missing, malformed, and cross-principal credentials all use
      // the same generic session-not-found response.
      writeMcpError(response, 404, -32001, "Session not found");
      return;
    }
    if (!sameBinding(entry.binding, binding)) {
      writeMcpError(response, 404, -32001, "Session not found");
      return;
    }

    if (this.grantSessionBindingStore?.get !== undefined) {
      const durableBinding = await this.grantSessionBindingStore.get(grantKeyFromBinding(binding));
      if (durableBinding === null || durableBinding.status !== "active" || durableBinding.agentSessionId !== entry.agentSessionId) {
        // Treat revocation, expiry, and a mapping mismatch as generic opaque
        // session-not-found. The caller cannot use this route to enumerate a
        // valid grant or an Agent Farm session owned by another principal.
        await this.removeEntry(entry);
        writeMcpError(response, 404, -32001, "Session not found");
        return;
      }
    }

    entry.lastActivityAt = this.now();
    const originalAuth = request.auth;
    if (originalAuth !== undefined) {
      // Only this request-scoped clone carries the manager-selected session.
      // The registry stores the identity tuple, never this AuthInfo/token.
      request.auth = { ...originalAuth, extra: { ...(originalAuth.extra ?? {}), agentSessionId: entry.agentSessionId } };
    }
    try {
      await entry.transport.handleRequest(request, response, parsedBody);
    } catch (error) {
      // Keep protocol state on ordinary request/tool errors. DELETE and
      // explicit eviction remove the entry through the SDK callback/manager.
      throw error;
    } finally {
      if (originalAuth === undefined) delete request.auth;
      else request.auth = originalAuth;
    }
  }

  private async resolveGrantSessionBinding(
    binding: SessionBinding,
    proposedAgentSessionId: string,
    authInfo: AuthInfo | undefined,
  ): Promise<McpGrantSessionBindingRecord | null | undefined> {
    const store = this.grantSessionBindingStore;
    if (store === undefined) return undefined;
    return await store.getOrCreate({
      ...grantKeyFromBinding(binding),
      proposedAgentSessionId,
      ...(authInfo?.expiresAt === undefined ? {} : { expiresAt: authInfo.expiresAt * 1_000 }),
    });
  }

  private async register(entry: SessionEntry): Promise<void> {
    if (this.closed) {
      await closeApplication(entry.application);
      await closeTransport(entry.transport);
      throw new Error("MCP session manager is closed");
    }
    await this.evictExpired();
    if (this.entries.has(entry.mcpSessionId)) {
      await closeApplication(entry.application);
      await closeTransport(entry.transport);
      throw new Error("MCP session ID collision");
    }
    while (this.entries.size >= this.maxSessions) {
      const oldest = oldestEntry(this.entries);
      if (oldest === undefined) break;
      await this.removeEntry(oldest);
    }
    this.entries.set(entry.mcpSessionId, entry);
  }

  private isExpired(entry: SessionEntry): boolean {
    return this.now() - entry.lastActivityAt >= this.sessionTtlMs;
  }

  private async evictExpired(): Promise<void> {
    const expired = [...this.entries.values()].filter((entry) => this.isExpired(entry));
    for (const entry of expired) await this.removeEntry(entry);
  }

  private evictExpiredSync(): void {
    for (const entry of [...this.entries.values()]) {
      if (!this.isExpired(entry)) continue;
      this.entries.delete(entry.mcpSessionId);
      entry.closed = true;
      void closeApplication(entry.application);
    }
  }

  private async removeEntry(entry: SessionEntry): Promise<void> {
    if (this.entries.get(entry.mcpSessionId) !== entry) return;
    this.entries.delete(entry.mcpSessionId);
    entry.closed = true;
    await closeApplication(entry.application);
  }

  private async closeEntry(entry: SessionEntry, closeTransportAfterApplication: boolean): Promise<void> {
    entry.closed = true;
    await closeApplication(entry.application);
    if (closeTransportAfterApplication) await closeTransport(entry.transport);
  }
}

export function createMcpHttpSessionManager(
  options: McpHttpSessionManagerOptions,
): McpHttpSessionManager {
  return new McpHttpSessionManager(options);
}

/**
 * Direct Node adapters often pass an application factory inline. Cache the
 * manager by function identity so this compatibility path remains stateful;
 * the Fastify composition root uses an explicit manager and cleanup hook.
 */
const compatibilityManagers = new WeakMap<McpHttpApplicationFactory, McpHttpSessionManager>();

export async function handleMcpHttpRequest(
  request: McpNodeRequest,
  response: ServerResponse,
  parsedBody: unknown,
  options: McpHttpHandlerOptions,
): Promise<void> {
  const manager = options.sessionManager ?? managerForCompatibility(options.applicationFactory);
  await manager.handleRequest(request, response, parsedBody, options);
}

function managerForCompatibility(
  factory: McpHttpApplicationFactory | undefined,
): McpHttpSessionManager {
  if (factory === undefined) throw new Error("MCP session manager is required");
  const prior = compatibilityManagers.get(factory);
  if (prior !== undefined) return prior;
  const manager = new McpHttpSessionManager({ applicationFactory: factory });
  compatibilityManagers.set(factory, manager);
  return manager;
}

function toTransportOptions(
  options: Omit<McpHttpHandlerOptions, "sessionManager" | "applicationFactory">,
): TransportOptions {
  return {
    enableJsonResponse: options.enableJsonResponse ?? true,
    ...(options.allowedHosts === undefined ? {} : { allowedHosts: options.allowedHosts }),
    ...(options.allowedOrigins === undefined ? {} : { allowedOrigins: options.allowedOrigins }),
    ...(options.keepAliveMs === undefined ? {} : { keepAliveMs: options.keepAliveMs }),
  };
}

function bindingFromAuthInfo(authInfo: AuthInfo | undefined): SessionBinding | undefined {
  if (authInfo === undefined) return undefined;
  const extra = authInfo.extra ?? {};
  // The generic OAuth grant must not select the MCP/Agent Farm session. That
  // authority is generated by this manager at initialize and injected only
  // into the request-scoped AuthInfo clone for subsequent tool execution.
  // Reject both spellings, including malformed values, rather than silently
  // overriding a pre-bound token claim.
  if (Object.prototype.hasOwnProperty.call(extra, "agentSessionId") || Object.prototype.hasOwnProperty.call(extra, "agent_session_id")) {
    return undefined;
  }
  const ownerId = claim(extra, ["ownerId", "owner_id"]);
  const tenantId = claim(extra, ["tenantId", "tenant_id"]);
  const subject = claim(extra, ["sub"]) ?? boundedOptional(authInfo.clientId);
  const grantId = claim(extra, ["sid", "grantId", "grant_id"]);
  const jti = claim(extra, ["jti", "tokenId", "token_id"]);
  const resource = canonicalResource(authInfo.resource);
  if (
    ownerId === undefined ||
    tenantId === undefined ||
    subject === undefined ||
    grantId === undefined ||
    jti === undefined ||
    resource === undefined
  ) {
    return undefined;
  }
  return { ownerId, tenantId, subject, grantId, jti, resource };
}

function claim(extra: Record<string, unknown>, keys: readonly string[]): string | undefined {
  for (const key of keys) {
    const value = extra[key];
    if (typeof value === "string" && value.trim().length > 0 && value.length <= MAX_CLAIM_LENGTH) return value;
  }
  return undefined;
}

function boundedOptional(value: string | undefined): string | undefined {
  return typeof value === "string" && value.trim().length > 0 && value.length <= MAX_CLAIM_LENGTH ? value : undefined;
}

function canonicalResource(resource: URL | string | undefined): string | undefined {
  if (resource === undefined) return undefined;
  try {
    const value = new URL(resource.toString());
    if (value.protocol !== "https:" && value.protocol !== "http:") return undefined;
    value.hash = "";
    return value.toString();
  } catch {
    return undefined;
  }
}

function sameBinding(left: SessionBinding, right: SessionBinding): boolean {
  // jti is required and verified on every request, but OAuth refresh may
  // rotate it while preserving the owner/tenant/subject/resource/grant tuple.
  // The MCP session therefore binds to that stable grant tuple, not one JWT.
  return (
    left.ownerId === right.ownerId &&
    left.tenantId === right.tenantId &&
    left.subject === right.subject &&
    left.grantId === right.grantId &&
    left.resource === right.resource
  );
}

function grantKeyFromBinding(binding: SessionBinding): McpGrantSessionBindingKey {
  return {
    ownerId: binding.ownerId,
    tenantId: binding.tenantId,
    subject: binding.subject,
    resource: binding.resource,
    grantId: binding.grantId,
  };
}

function readMcpSessionId(request: McpNodeRequest): { present: boolean; value?: string | undefined } {
  const raw = request.headers["mcp-session-id"];
  if (raw === undefined) return { present: false };
  if (Array.isArray(raw)) return raw.length === 1 ? { present: true, value: boundedOptional(raw[0]) } : { present: true };
  return { present: true, value: boundedOptional(raw) };
}

function containsInitializeRequest(body: unknown): boolean {
  const messages = Array.isArray(body) ? body : [body];
  return messages.some((message) => {
    if (typeof message !== "object" || message === null || Array.isArray(message)) return false;
    return (message as { method?: unknown }).method === "initialize";
  });
}

function oldestEntry(entries: Map<string, SessionEntry>): SessionEntry | undefined {
  let oldest: SessionEntry | undefined;
  for (const entry of entries.values()) {
    if (oldest === undefined || entry.lastActivityAt < oldest.lastActivityAt) oldest = entry;
  }
  return oldest;
}

function boundedOpaqueId(value: string, label: string): string {
  if (typeof value !== "string" || value.trim().length === 0 || value.length > MAX_SESSION_ID_LENGTH) {
    throw new Error(`${label} is invalid`);
  }
  return value;
}

function boundedPositive(value: number, label: string): number {
  if (!Number.isFinite(value) || value <= 0) throw new TypeError(`${label} must be positive`);
  return value;
}

function boundedPositiveInteger(value: number, label: string): number {
  if (!Number.isSafeInteger(value) || value <= 0) throw new TypeError(`${label} must be a positive integer`);
  return value;
}

async function connectApplication(application: McpApplication, transport: StreamableHTTPServerTransport): Promise<void> {
  await application.server.connect(
    transport as unknown as Parameters<typeof application.server.connect>[0],
  );
}

async function closeApplication(application: McpApplication): Promise<void> {
  try {
    await application.server.close();
  } catch {
    // Best effort during expiry/DELETE/shutdown; protocol response must win.
  }
}

async function closeTransport(transport: StreamableHTTPServerTransport): Promise<void> {
  try {
    await transport.close();
  } catch {
    // Best effort during candidate cleanup or shutdown.
  }
}

function writeMcpError(response: ServerResponse, status: number, code: number, message: string): void {
  if (response.headersSent || response.writableEnded) return;
  response.statusCode = status;
  response.setHeader("content-type", "application/json");
  response.setHeader("cache-control", "no-store");
  response.end(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code, message } }));
}

function assertPublicApplication(application: McpApplication): void {
  const names = application.descriptors.map((descriptor) => descriptor.name);
  if (
    names.length !== AGENT_FARM_MCP_TOOL_NAMES.length ||
    AGENT_FARM_MCP_TOOL_NAMES.some((name) => !names.includes(name))
  ) {
    throw new Error(`Agent Farm MCP application must expose exactly ${AGENT_FARM_MCP_TOOL_NAMES.length} tools`);
  }
  if (application.resourceUri.length === 0 || application.resourceUri !== AGENT_HIERARCHY_RESOURCE_URI) {
    // A custom UI resource is valid for embedding, but an empty URI is not.
    if (application.resourceUri.length === 0) throw new Error("Agent Farm MCP resource URI is required");
  }
}
